// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['limbonia']['LimboniaApp']['CheckForUpdate']();
}

export function CheckLimboniaVersion() {
  return window['go']['limbonia']['LimboniaApp']['CheckLimboniaVersion']();
}

export function DownloadLimbonia() {
  return window['go']['limbonia']['LimboniaApp']['DownloadLimbonia']();
}

export function GetChangelog() {
  return window['go']['limbonia']['LimboniaApp']['GetChangelog']();
}

export function GetConfig() {
  return window['go']['limbonia']['LimboniaApp']['GetConfig']();
}

export function GetServerVersion() {
  return window['go']['limbonia']['LimboniaApp']['GetServerVersion']();
}

export function OpenFileDialog() {
  return window['go']['limbonia']['LimboniaApp']['OpenFileDialog']();
}

export function OpenMephi() {
  return window['go']['limbonia']['LimboniaApp']['OpenMephi']();
}

export function Startup(arg1) {
  return window['go']['limbonia']['LimboniaApp']['Startup'](arg1);
}
