// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {client} from '../models';
import {config} from '../models';
import {updater} from '../models';
import {context} from '../models';

export function CheckForUpdate():Promise<boolean>;

export function CheckLimboniaVersion():Promise<boolean>;

export function DownloadLimbonia():Promise<void>;

export function GetChangelog():Promise<Array<client.ChangelogEntry>>;

export function GetConfig():Promise<config.Config>;

export function GetServerVersion():Promise<updater.UpdateResponse>;

export function OpenFileDialog():Promise<string>;

export function OpenMephi():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
