// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['limbonia']['LimboniaApp']['CheckForUpdate']();
}

export function CheckLimboniaVersion() {
  return window['go']['limbonia']['LimboniaApp']['CheckLimboniaVersion']();
}

export function DownloadBotQuixote() {
  return window['go']['limbonia']['LimboniaApp']['DownloadBotQuixote']();
}

export function DownloadLimbonia() {
  return window['go']['limbonia']['LimboniaApp']['DownloadLimbonia']();
}

export function DownloadUpdate(arg1, arg2) {
  return window['go']['limbonia']['LimboniaApp']['DownloadUpdate'](arg1, arg2);
}

export function ExtractFile() {
  return window['go']['limbonia']['LimboniaApp']['ExtractFile']();
}

export function GetConfig() {
  return window['go']['limbonia']['LimboniaApp']['GetConfig']();
}

export function GetServerVersion() {
  return window['go']['limbonia']['LimboniaApp']['GetServerVersion']();
}

export function OpenBotQuixote() {
  return window['go']['limbonia']['LimboniaApp']['OpenBotQuixote']();
}

export function OpenFileDialog() {
  return window['go']['limbonia']['LimboniaApp']['OpenFileDialog']();
}

export function Startup(arg1) {
  return window['go']['limbonia']['LimboniaApp']['Startup'](arg1);
}
