// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {updater} from '../models';
import {context} from '../models';

export function CheckForUpdate():Promise<boolean>;

export function CheckLimboniaVersion():Promise<boolean>;

export function DownloadBotQuixote():Promise<void>;

export function DownloadLimbonia():Promise<void>;

export function DownloadUpdate(arg1:string,arg2:string):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetServerVersion():Promise<updater.UpdateResponse>;

export function OpenBotQuixote():Promise<void>;

export function OpenFileDialog():Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;
