// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForDiscordDll():Promise<void>;

export function DownloadLauncher():Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function InjectLimbonia():Promise<void>;

export function OpenLimboniaFolder():Promise<void>;

export function OpenLimbusFolder():Promise<void>;

export function OpenSettingsFolder():Promise<void>;
