// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteLimboniaDLL() {
  return window['go']['main']['App']['DeleteLimboniaDLL']();
}

export function DownloadLauncher() {
  return window['go']['main']['App']['DownloadLauncher']();
}

export function InjectLimbonia() {
  return window['go']['main']['App']['InjectLimbonia']();
}

export function IsGameRunning() {
  return window['go']['main']['App']['IsGameRunning']();
}

export function IsLinux() {
  return window['go']['main']['App']['IsLinux']();
}

export function LauncherUpdateState() {
  return window['go']['main']['App']['LauncherUpdateState']();
}

export function LauncherVersion() {
  return window['go']['main']['App']['LauncherVersion']();
}

export function OpenLimboniaFolder() {
  return window['go']['main']['App']['OpenLimboniaFolder']();
}

export function OpenLimbusFolder() {
  return window['go']['main']['App']['OpenLimbusFolder']();
}

export function OpenSettingsFolder() {
  return window['go']['main']['App']['OpenSettingsFolder']();
}

export function RestartLauncher() {
  return window['go']['main']['App']['RestartLauncher']();
}
