// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadLauncher() {
  return window['go']['main']['App']['DownloadLauncher']();
}

export function InjectLimbonia() {
  return window['go']['main']['App']['InjectLimbonia']();
}

export function OpenLimboniaFolder() {
  return window['go']['main']['App']['OpenLimboniaFolder']();
}

export function OpenLimbusFolder() {
  return window['go']['main']['App']['OpenLimbusFolder']();
}

export function OpenSettingsFolder() {
  return window['go']['main']['App']['OpenSettingsFolder']();
}
